/*
 * PaperPluginTemplate
 *
 * Copyright (c) 2026. Namiu (うにたろう)
 *                     Contributors []
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package io.github.namiuni.paperplugintemplate.minecraft.paper;

import io.papermc.paper.plugin.loader.PluginClasspathBuilder;
import io.papermc.paper.plugin.loader.PluginLoader;
import org.jspecify.annotations.NullMarked;
import xyz.jpenilla.gremlin.runtime.platformsupport.DefaultsPaperPluginLoader;

/// Paper [PluginLoader] that resolves runtime dependencies declared in
/// `dependencies.txt` (generated by the Gremlin Gradle plugin) and appends them
/// to the plugin's classpath before the server loads any plugin classes.
///
/// This class is referenced in `paper-plugin.yml` via the `loader` key and is
/// instantiated by the Paper server before [PluginBootstrapImpl] or [JavaPluginImpl].
@NullMarked
@SuppressWarnings({"UnstableApiUsage", "unused"})
public final class PluginLoaderImpl implements PluginLoader {

    /// {@inheritDoc}
    @Override
    public void classloader(final PluginClasspathBuilder classpathBuilder) {
        new DefaultsPaperPluginLoader().classloader(classpathBuilder);
    }
}
